version: '3'

services:
  
  postgresql:
    image: postgres:13
    container_name: postgresql
    hostname: postgresql
    restart: unless-stopped
    networks:
      - atlassiannet
    volumes:
      - ./postgre/create-db.sh:/opt/create-db.sh
      - /var/postgresql/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=QksuYejx_speI93'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
  
  jira:
    image: atlassian/jira-software:latest
    container_name: jira
    hostname: jira
    restart: unless-stopped
    depends_on:
      - postgresql
    networks:
      - atlassiannet
    volumes:
      - jiradata:/var/atlassian/application-data/jira
    ports:
      - '8080:8080'
    environment:
      - 'ATL_JDBC_URL=postgresql://jirauser@postgresql/jiradb'
      - 'ATL_JDBC_PASSWORD=Jiraydroneslab2022'
      - 'JVM_MINIMUM_MEMORY=1g'
      - 'JVM_MAXIMUM_MEMORY=2g'
      - 'ATL_PROXY_NAME=10.13.14.127'
      - 'ATL_PROXY_PORT=80'
      - 'ATL_TOMCAT_CONTEXTPATH=/jira'
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
  
  bitbucket:
    image: atlassian/bitbucket:latest
    container_name: bitbucket
    hostname: bitbucket
    restart: unless-stopped
    depends_on:
      - postgresql
    networks:
      - atlassiannet
    volumes:
      - bitbucketdata:/var/atlassian/bitbucket
    ports:
      - '7990:7990'
    environment:
      - 'JDBC_URL=postgresql://bitbucketuser@postgresql/jiradb'
      - 'JDBC_PASSWORD=Bitbucketydroneslab2022'
      - 'JVM_MINIMUM_MEMORY=1g'
      - 'JVM_MAXIMUM_MEMORY=2g'
      - 'SERVER_PROXY_NAME=10.13.14.127'
      - 'SERVER_PROXY_PORT=80'

  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    networks:
      - atlassiannet
    volumes:
      - nginxdata:/home/nginx
      - nginxwww:/var/lib/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

volumes:
  jiradata:
    external: true
  bitbucketdata:
    external: true
  nginxdata:
    external: true
  nginxwww:
    external: true

networks:
  atlassiannet:
    name: network-atlassian