version: '3'

services:
  
  postgresql:
    image: postgres:13
    container_name: postgresql
    hostname: postgresql
    restart: unless-stopped
    networks:
      - atlassiannet
    volumes:
      - ./postgre/create-db.sh:/opt/create-db.sh
      - /var/postgresql/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=QksuYejx_speI93'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    entrypoint: ["sh","/opt/create-db.sh"]
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
  
  jira:
    image: atlassian/jira-software:latest
    container_name: jira
    hostname: jira
    restart: unless-stopped
    depends_on:
      - postgresql
    networks:
      - atlassiannet
    volumes:
      - jiradata:/var/atlassian/application-data/jira
    ports:
      - '8080:8080'
    environment:
      - 'ATL_JDBC_URL=postgresql://jira@postgresql/jiradb'
      - 'ATL_JDBC_PASSWORD=Jiraydroneslab2022'
      - 'JVM_MINIMUM_MEMORY=1g'
      - 'JVM_MAXIMUM_MEMORY=2g'
      - 'ATL_PROXY_NAME=10.13.14.127'
      - 'ATL_PROXY_PORT=80'
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
  
  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    networks:
      - atlassiannet
    volumes:
      - nginxdata:/home/nginx
      - nginxwww:/var/lib/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

volumes:
  jiradata:
    external: true
  nginxdata:
    external: true
  nginxwww:
    external: true

networks:
  atlassiannet:
    name: network-atlassian