version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    networks:
      - atlassiannet
    volumes:
      - nginxdata:/home/nginx
      - nginxwww:/var/lib/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

volumes:
  nginxdata:
    external: true
  nginxwww:
    external: true

networks:
  atlassiannet:
      name: network-atlassian