version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    networks:
      - atlassiannet
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

volumes:
  jiradata:
    external: true

networks:
  atlassiannet:
      name: network-atlassian