version: '3'

services:
  jira:
    image: atlassian/jira-software:latest
    container_name: jira
    hostname: jira
    restart: unless-stopped
    networks:
      - atlassiannet
    volumes:
      - jiradata:/var/atlassian/application-data/jira
    ports:
      - '8080:8080'
    environment:
      - 'ATL_JDBC_URL=postgresql://jira@postgresql/jiradb'
      - 'ATL_JDBC_PASSWORD=Jiraydroneslab2022'
      - 'JVM_MINIMUM_MEMORY=1g'
      - 'JVM_MAXIMUM_MEMORY=2g'
      - 'ATL_PROXY_NAME=10.13.14.127'
      - 'ATL_PROXY_PORT=8080'
      - 'ATL_TOMCAT_CONTEXTPATH=/jira'
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

volumes:
  jiradata:
    external: true

networks:
  atlassiannet:
      name: network-atlassian